### ISSUE TITLE
Error loading script: shutdown.py

### ISSUE THREAD

**Issue by mdogancay** [EnsignMK/sd_shutdown_button#3]
*** Error loading script: shutdown.py
    Traceback (most recent call last):
      File "F:\AI\sd-webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\AI\sd-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\AI\sd-webui\extensions\sd_shutdown_button\scripts\shutdown.py", line 53, in <module>
        key = opts.data["quicksettings_list"][-1]
    KeyError: 'quicksettings_list'

**Comment by niekumam** [comment]
It's similar for me:
```
*** Error loading script: shutdown.py
    Traceback (most recent call last):
      File "E:\git\zip\webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\git\zip\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\git\zip\webui\extensions\sd_shutdown_button\scripts\shutdown.py", line 52, in <module>
        key = opts.data["quicksettings_list"][-1]
    KeyError: 'quicksettings_list'
```
I spend a while for searching the issue but without success...

**Comment by EnsignMK** [comment]
@niekumam @mdogancay  Thanks for reporting it's a known issue,  I  have hardcoded 
some parts of the extension which became outdated after couple of version updates of the webui.
I will look into to see how I can resolve it quickly,you will receive an update

**Comment by EnsignMK** [comment]
@niekumam @mdogancay  It works now ,update to the latest version of the extension
